/**
 * Audio Controls Store
 *
 * Replaces useAudioControls hook. Manages all audio playback state globally so
 * SpeckleScene, SoundGenerationSection, WaveSurferTimeline, and EntityInfoPanel
 * can all read from one source of truth without prop drilling through page.tsx.
 *
 * Sync:  page.tsx must call syncGeneratedSounds() whenever soundGen.generatedSounds
 *        changes so that playAll / stopAll / handleVariantChange / handleIntervalChange
 *        have the correct sound list available.
 *
 * zundo partializes on: soundVolumes, soundIntervals, selectedVariants, mutedSounds,
 *                       soloedSound  (the "user-facing" config — excludes play state).
 */

import { create } from 'zustand';
import { temporal } from 'zundo';
import { devtools } from 'zustand/middleware';
import type { SoundState } from '@/types';
import type { IterationLink } from '@/types/audio';
import { AUDIO_PLAYBACK, DEFAULT_SPL_DB, DEFAULT_MAXIMUM_FOLEY_SOUNDS } from '@/utils/constants';

export interface AudioControlsStoreState {
  // ── State ──
  individualSoundStates: Record<string, SoundState>;
  selectedVariants: Record<number, number>;
  soundVolumes: Record<string, number>;
  soundIntervals: Record<string, number>;
  soundTrims: Record<string, { start: number; end: number }>;
  mutedSounds: Set<string>;
  soloedSound: string | null;
  previewingSoundId: string | null;
  /** Absolute jitter applied to each iteration's playback interval (seconds). */
  intervalJitterSeconds: number;
  /** Fixed timeline length in milliseconds — both visual and audio are bounded to this. */
  timelineDurationMs: number;
  /** Internal: synced from useSoundGeneration. Used by playAll / stopAll / handleVariantChange. */
  _generatedSounds: any[];
  /** Per-sound scheduling mode: 'interval' (default) or 'timestamps'. */
  soundSchedulingModes: Record<string, 'interval' | 'timestamps'>;
  /** Per-sound explicit playback timestamps in seconds (used when mode is 'timestamps'). */
  soundTimestamps: Record<string, number[]>;
  /**
   * Per-iteration overrides.  Key = `${soundId}-${iterationIndex}`.
   * Stores variant and/or entity overrides for individual DAW blocks.
   */
  iterationLinks: Record<string, IterationLink>;

  // ── Sync ──
  syncGeneratedSounds: (sounds: any[]) => void;

  // ── Actions ──
  toggleSound: (soundId: string) => void;
  handleVariantChange: (promptIdx: number, variantIdx: number) => void;
  handleVolumeChange: (soundId: string, volumeDb: number) => void;
  handleIntervalChange: (soundId: string, intervalSeconds: number) => void;
  handleSchedulingModeChange: (soundId: string, mode: 'interval' | 'timestamps', soundDurationSeconds?: number) => void;
  handleTimestampsChange: (soundId: string, timestamps: number[]) => void;
  handleRemoveTimestamp: (soundId: string, iterationIndex: number) => void;
  setIterationLink: (soundId: string, iterationIndex: number, link: Partial<IterationLink>) => void;
  clearIterationLink: (soundId: string, iterationIndex: number) => void;
  clearAllIterationLinksForSound: (soundId: string) => void;
  handleMute: (soundId: string) => void;
  handleSolo: (soundId: string) => void;
  setSoundTrim: (soundId: string, trim: { start: number; end: number }) => void;
  setIntervalJitter: (seconds: number) => void;
  setTimelineDurationMs: (ms: number) => void;
  resetTimelineDurationMs: () => void;
  /** Global base SPL reference level for all generated sounds (dB). */
  globalBaseSplDb: number;
  setGlobalBaseSplDb: (db: number) => void;
  resetGlobalBaseSplDb: () => void;
  /** Maximum number of foley sound events generated by the foley artist. */
  maximumFoleySounds: number;
  setMaximumFoleySounds: (n: number) => void;
  handlePreviewPlayPause: (soundId: string) => void;
  handlePreviewStop: (soundId: string) => void;
  stopSoundcardPreview: () => void;
  playAll: () => void;
  pauseAll: () => void;
  stopAll: () => void;
  isAnyPlaying: () => boolean;
  forceStopAll: () => void;
  restoreVolumeAndIntervals: (
    volumes: Record<string, number>,
    intervals: Record<string, number>,
  ) => void;
}

// ─── Partialize (exported for snapshot registry) ───────────────────────────

export const audioControlsPartialize = (state: AudioControlsStoreState) => ({
  soundVolumes: { ...state.soundVolumes },
  soundIntervals: { ...state.soundIntervals },
  soundTrims: { ...state.soundTrims },
  selectedVariants: { ...state.selectedVariants },
  mutedSounds: new Set(state.mutedSounds),
  soloedSound: state.soloedSound,
  intervalJitterSeconds: state.intervalJitterSeconds,
  timelineDurationMs: state.timelineDurationMs,
  globalBaseSplDb: state.globalBaseSplDb,
  maximumFoleySounds: state.maximumFoleySounds,
  soundSchedulingModes: { ...state.soundSchedulingModes },
  soundTimestamps: { ...state.soundTimestamps },
});

export const useAudioControlsStore = create<AudioControlsStoreState>()(
  temporal(
    devtools(
      (set, get) => ({
        // ── Initial state ──
        individualSoundStates: {},
        selectedVariants: {},
        soundVolumes: {},
        soundIntervals: {},
        soundTrims: {},
        mutedSounds: new Set(),
        soloedSound: null,
        previewingSoundId: null,
        intervalJitterSeconds: AUDIO_PLAYBACK.DEFAULT_INTERVAL_JITTER_SECONDS,
        timelineDurationMs: AUDIO_PLAYBACK.TIMELINE_FIXED_DURATION_MS,
        globalBaseSplDb: DEFAULT_SPL_DB,
        maximumFoleySounds: DEFAULT_MAXIMUM_FOLEY_SOUNDS,
        _generatedSounds: [],
        soundSchedulingModes: {},
        soundTimestamps: {},
        iterationLinks: {},

        // ── Sync ──
        syncGeneratedSounds: (sounds) =>
          set({ _generatedSounds: sounds }, false, 'audio/syncGeneratedSounds'),

        // ── Actions ──
        toggleSound: (soundId) =>
          set(
            (state) => {
              const current = state.individualSoundStates[soundId] || 'stopped';
              return {
                individualSoundStates: {
                  ...state.individualSoundStates,
                  [soundId]: current === 'playing' ? 'paused' : 'playing',
                },
              };
            },
            false,
            'audio/toggleSound',
          ),

        handleVariantChange: (promptIdx, variantIdx) => {
          // Timeline playback is intentionally decoupled from the card variant selector.
          // Only update selectedVariants (drives sphere display + card preview) and
          // transfer the preview sound ID if the user was previewing the old variant.
          // individualSoundStates is NOT touched so the timeline keeps playing variant 0.
          const { _generatedSounds, selectedVariants, previewingSoundId } = get();

          const byPrompt: Record<number, any[]> = {};
          _generatedSounds.forEach((s) => {
            const idx = s.prompt_index ?? 0;
            if (!byPrompt[idx]) byPrompt[idx] = [];
            byPrompt[idx].push(s);
          });

          const sounds = byPrompt[promptIdx];
          if (!sounds) return;

          const oldVariantIdx = selectedVariants[promptIdx] || 0;
          const oldSound = sounds[oldVariantIdx];
          const newSound = sounds[variantIdx];
          const wasPreviewPlaying = oldSound && previewingSoundId === oldSound.id;

          set(
            {
              selectedVariants: { ...selectedVariants, [promptIdx]: variantIdx },
              previewingSoundId:
                wasPreviewPlaying && newSound ? newSound.id : previewingSoundId,
            },
            false,
            'audio/handleVariantChange',
          );
        },

        handleVolumeChange: (soundId, volumeDb) =>
          set(
            (state) => ({ soundVolumes: { ...state.soundVolumes, [soundId]: volumeDb } }),
            false,
            'audio/handleVolumeChange',
          ),

        handleIntervalChange: (soundId, intervalSeconds) => {
          get().stopAll();
          set(
            (state) => ({
              soundIntervals: { ...state.soundIntervals, [soundId]: intervalSeconds },
            }),
            false,
            'audio/handleIntervalChange',
          );
        },

        handleSchedulingModeChange: (soundId, mode, soundDurationSeconds) => {
          get().stopAll();
          set(
            (state) => {
              let newTimestamps = { ...state.soundTimestamps };

              if (mode === 'timestamps') {
                // Auto-generate timestamps packed tightly (gap = 0) from t=0 up to the
                // timeline duration.  Use the actual buffer duration if provided so
                // sounds sit exactly back-to-back; fall back to a single t=0 sentinel
                // so the list is never empty.
                const timelineDurationSec = state.timelineDurationMs / 1000;
                const autoTs: number[] = [];
                if (soundDurationSeconds && soundDurationSeconds > 0) {
                  let t = 0;
                  while (t + soundDurationSeconds <= timelineDurationSec && autoTs.length < 200) {
                    autoTs.push(parseFloat(t.toFixed(3)));
                    t += soundDurationSeconds;
                  }
                }
                // Always seed at least one timestamp
                if (autoTs.length === 0) autoTs.push(0);
                newTimestamps = { ...newTimestamps, [soundId]: autoTs };
              } else {
                // Switching back to interval mode — clear the timestamps
                const { [soundId]: _removed, ...rest } = newTimestamps;
                newTimestamps = rest;
              }

              return {
                soundSchedulingModes: { ...state.soundSchedulingModes, [soundId]: mode },
                soundTimestamps: newTimestamps,
              };
            },
            false,
            'audio/handleSchedulingModeChange',
          );
        },

        handleTimestampsChange: (soundId, timestamps) => {
          get().stopAll();
          set(
            (state) => ({
              soundTimestamps: { ...state.soundTimestamps, [soundId]: timestamps },
            }),
            false,
            'audio/handleTimestampsChange',
          );
        },

        handleRemoveTimestamp: (soundId, iterationIndex) =>
          set(
            (state) => {
              const timestamps = state.soundTimestamps[soundId] ?? [];
              const newTimestamps = timestamps.filter((_, i) => i !== iterationIndex);
              return { soundTimestamps: { ...state.soundTimestamps, [soundId]: newTimestamps } };
            },
            false,
            'audio/handleRemoveTimestamp',
          ),

        setIterationLink: (soundId, iterationIndex, link) =>
          set(
            (state) => {
              const key = `${soundId}-${iterationIndex}`;
              const existing = state.iterationLinks[key] ?? {};
              return { iterationLinks: { ...state.iterationLinks, [key]: { ...existing, ...link } } };
            },
            false,
            'audio/setIterationLink',
          ),

        clearIterationLink: (soundId, iterationIndex) =>
          set(
            (state) => {
              const key = `${soundId}-${iterationIndex}`;
              const { [key]: _removed, ...rest } = state.iterationLinks;
              return { iterationLinks: rest };
            },
            false,
            'audio/clearIterationLink',
          ),

        clearAllIterationLinksForSound: (soundId) =>
          set(
            (state) => {
              const prefix = `${soundId}-`;
              const filtered = Object.fromEntries(
                Object.entries(state.iterationLinks).filter(([k]) => !k.startsWith(prefix)),
              );
              return { iterationLinks: filtered };
            },
            false,
            'audio/clearAllIterationLinksForSound',
          ),

        handleMute: (soundId) =>
          set(
            (state) => {
              const newMuted = new Set(state.mutedSounds);
              newMuted.has(soundId) ? newMuted.delete(soundId) : newMuted.add(soundId);
              return {
                mutedSounds: newMuted,
                soloedSound: state.soloedSound === soundId ? null : state.soloedSound,
              };
            },
            false,
            'audio/handleMute',
          ),

        handleSolo: (soundId) =>
          set(
            (state) => {
              const newMuted = new Set(state.mutedSounds);
              newMuted.delete(soundId);
              return {
                mutedSounds: newMuted,
                soloedSound: state.soloedSound === soundId ? null : soundId,
              };
            },
            false,
            'audio/handleSolo',
          ),

        setSoundTrim: (soundId, trim) =>
          set(
            (state) => ({ soundTrims: { ...state.soundTrims, [soundId]: trim } }),
            false,
            'audio/setSoundTrim',
          ),

        setIntervalJitter: (seconds) =>
          set({ intervalJitterSeconds: seconds }, false, 'audio/setIntervalJitter'),

        setTimelineDurationMs: (ms) =>
          set({ timelineDurationMs: ms }, false, 'audio/setTimelineDurationMs'),

        resetTimelineDurationMs: () =>
          set({ timelineDurationMs: AUDIO_PLAYBACK.TIMELINE_FIXED_DURATION_MS }, false, 'audio/resetTimelineDurationMs'),

        setGlobalBaseSplDb: (db) =>
          set({ globalBaseSplDb: db }, false, 'audio/setGlobalBaseSplDb'),

        resetGlobalBaseSplDb: () =>
          set({ globalBaseSplDb: DEFAULT_SPL_DB }, false, 'audio/resetGlobalBaseSplDb'),

        setMaximumFoleySounds: (n) =>
          set({ maximumFoleySounds: n }, false, 'audio/setMaximumFoleySounds'),

        handlePreviewPlayPause: (soundId) => {
          const { individualSoundStates } = get();
          if (Object.values(individualSoundStates).some((s) => s === 'playing')) {
            const stopped: Record<string, SoundState> = {};
            Object.keys(individualSoundStates).forEach((id) => { stopped[id] = 'stopped'; });
            set({ individualSoundStates: stopped }, false, 'audio/previewStopTimeline');
          }
          set(
            (state) => ({
              previewingSoundId:
                state.previewingSoundId === soundId ? null : soundId,
            }),
            false,
            'audio/handlePreviewPlayPause',
          );
        },

        handlePreviewStop: (soundId) =>
          set(
            (state) => ({
              previewingSoundId:
                state.previewingSoundId === soundId ? null : state.previewingSoundId,
            }),
            false,
            'audio/handlePreviewStop',
          ),

        stopSoundcardPreview: () =>
          set({ previewingSoundId: null }, false, 'audio/stopSoundcardPreview'),

        playAll: () => {
          set({ previewingSoundId: null }, false, 'audio/playAll/clearPreview');

          const { _generatedSounds } = get();

          const byPrompt: Record<number, any[]> = {};
          _generatedSounds.forEach((s) => {
            const idx = s.prompt_index ?? 0;
            if (!byPrompt[idx]) byPrompt[idx] = [];
            byPrompt[idx].push(s);
          });

          // Always play copy-index 0 (variant A) per prompt so that timeline playback
          // is completely independent of the sound card's variant selector.
          // The copy index is the trailing number in the sound ID (e.g. "generated_0_1" → 1).
          const copyIndexOf = (id: string): number => {
            const n = parseInt(id.split('_').pop() ?? '', 10);
            return isNaN(n) ? 0 : n;
          };

          set(
            (state) => {
              const newStates = { ...state.individualSoundStates };
              Object.entries(byPrompt).forEach(([, sounds]) => {
                // Stop all variants for this prompt first.
                sounds.forEach((s) => { newStates[s.id] = 'stopped'; });
                // Play the variant with the lowest copy index (variant A / the default).
                const sel = [...sounds].sort((a, b) => copyIndexOf(a.id) - copyIndexOf(b.id))[0];
                if (sel) newStates[sel.id] = 'playing';
              });
              return { individualSoundStates: newStates };
            },
            false,
            'audio/playAll',
          );
        },

        pauseAll: () =>
          set(
            (state) => {
              const newStates = { ...state.individualSoundStates };
              Object.keys(newStates).forEach((id) => {
                if (newStates[id] === 'playing') newStates[id] = 'paused';
              });
              return { individualSoundStates: newStates };
            },
            false,
            'audio/pauseAll',
          ),

        stopAll: () =>
          set(
            (state) => {
              // Stop ALL tracked sounds — not just _generatedSounds, which may lag behind
              // individualSoundStates and leave orphaned 'playing' entries that cause
              // the sync effect to restart the timeline after it ends naturally.
              const newStates: Record<string, SoundState> = {};
              Object.keys(state.individualSoundStates).forEach((id) => {
                newStates[id] = 'stopped';
              });
              return { individualSoundStates: newStates };
            },
            false,
            'audio/stopAll',
          ),

        isAnyPlaying: () =>
          Object.values(get().individualSoundStates).some((s) => s === 'playing'),

        forceStopAll: () =>
          set(
            { individualSoundStates: {}, soundVolumes: {}, soundIntervals: {} },
            false,
            'audio/forceStopAll',
          ),

        restoreVolumeAndIntervals: (volumes, intervals) =>
          set(
            { soundVolumes: volumes, soundIntervals: intervals },
            false,
            'audio/restoreVolumeAndIntervals',
          ),
      }),
      { name: 'AudioControlsStore' },
    ),
    {
      // Only record history for user-facing config (not play state / internal)
      partialize: audioControlsPartialize,
      equality: (past, current) =>
        JSON.stringify(past.soundVolumes) === JSON.stringify(current.soundVolumes) &&
        JSON.stringify(past.soundIntervals) === JSON.stringify(current.soundIntervals) &&
        JSON.stringify(past.soundTrims) === JSON.stringify(current.soundTrims) &&
        JSON.stringify(past.selectedVariants) === JSON.stringify(current.selectedVariants) &&
        past.mutedSounds.size === current.mutedSounds.size &&
        [...past.mutedSounds].every((id) => current.mutedSounds.has(id)) &&
        past.soloedSound === current.soloedSound &&
        past.intervalJitterSeconds === current.intervalJitterSeconds &&
        past.timelineDurationMs === current.timelineDurationMs &&
        past.globalBaseSplDb === current.globalBaseSplDb &&
        JSON.stringify(past.soundSchedulingModes) === JSON.stringify(current.soundSchedulingModes) &&
        JSON.stringify(past.soundTimestamps) === JSON.stringify(current.soundTimestamps),
    },
  ),
);
