import type { SidebarProps, SoundGenerationSectionProps } from '@/types/components';

/**
 * Map the page-level Sidebar props onto `SoundGenerationSection` props.
 * Shared by the expert Sidebar (Sounds step) and the Simple-mode scene panel,
 * so both render the exact same sound cards for a given parent usage card.
 */
export function buildSoundGenerationSectionProps(
  props: SidebarProps,
  visibleParentUsageIndex: number | null,
): SoundGenerationSectionProps {
  return {
    soundConfigs: props.soundConfigs,
    activeSoundConfigTab: props.activeSoundConfigTab,
    isSoundGenerating: props.isSoundGenerating,
    generatedSounds: props.generatedSounds,
    globalDuration: props.globalDuration,
    globalSteps: props.globalSteps,
    globalNegativePrompt: props.globalNegativePrompt,
    applyDenoising: props.applyDenoising,
    trimSilence: props.trimSilence,
    applyNoiseReduction: props.applyNoiseReduction,
    audioModel: props.audioModel,
    onSetActiveTab: props.setActiveSoundConfigTab,
    onAddConfig: props.onAddSoundConfig,
    onBatchAddConfigs: props.onBatchAddSoundConfigs,
    onRemoveConfig: props.onRemoveSoundConfig,
    onUpdateConfig: props.onUpdateSoundConfig,
    onTypeChange: props.onSoundTypeChange,
    onGenerate: props.onGenerateSounds,
    onGenerateSingle: props.onGenerateSingleSound,
    onGenerateFiltered: props.onGenerateFilteredSounds,
    onStopGeneration: props.onStopSoundGeneration,
    onGlobalDurationChange: props.onGlobalDurationChange,
    onGlobalStepsChange: props.onGlobalStepsChange,
    onGlobalNegativePromptChange: props.onGlobalNegativePromptChange,
    onApplyDenoisingChange: props.onApplyDenoisingChange,
    onTrimSilenceChange: props.onTrimSilenceChange,
    onApplyNoiseReductionChange: props.onApplyNoiseReductionChange,
    onAudioModelChange: props.onAudioModelChange,
    onReprocessSounds: props.onReprocessSounds,
    onUploadAudio: props.onUploadAudio,
    onClearUploadedAudio: props.onClearUploadedAudio,
    onLibrarySearch: props.onLibrarySearch,
    onLibrarySoundSelect: props.onLibrarySoundSelect,
    modelEntities: props.modelEntities,
    onStartLinkingEntity: props.onStartLinkingEntity,
    onCancelLinkingEntity: props.onCancelLinkingEntity,
    onFinishLinkingEntity: props.onFinishLinkingEntity,
    onSelectLinkedEntity: props.onSelectLinkedEntity,
    onClearLinkedEntities: props.onClearLinkedEntities,
    isLinkingEntity: props.isLinkingEntity,
    linkingConfigIndex: props.linkingConfigIndex,
    useSpeckleViewer: props.useSpeckleViewer,
    onDuplicateConfig: props.onDuplicateConfig,
    onRegenerateSingle: props.onRegenerateSingle,
    onDeleteVariant: props.onDeleteVariant,
    onSelectSoundCard: props.onSelectSoundCard,
    selectedCardIndex: props.selectedCardIndex,
    onSoundCardCollapsed: props.onSoundCardCollapsed,
    onCatalogSoundSelect: props.onCatalogSoundSelect,
    visibleParentUsageIndex,
  };
}
